<optgroup label="METALS">
<option value="Metal">Metal</option>
<option value="Brass">Brass</option>
<option value="Bronze">Bronze</option>
<option value="Ceramic plated">Ceramic plated</option>
<option value="Cobalt-Chrome">Cobalt-Chrome</option>
<option value="Copper">Copper</option>		
<option value="Niobium">Niobium</option>
<option value="Pewter">Pewter</option>
<option value="Rhodium plated">Rhodium plated</option>
<option value="Sterling Silver">Sterling Silver</option>
<option value="Sterling Silver plated">Sterling Silver plated</option>
<option value="316L Stainless Steel">316L Stainless Steel</option>
<option value="316LVM ASTM F-138 Implant Grade Steel">316LVM ASTM F-138 Implant Grade Steel</option>
<option value="PVD plated">PVD plated</option>
<option value="PVD plated steel">PVD plated steel</option>
<option value="Color plated steel">Color plated steel</option>
<option value="410 stainless steel">410 stainless steel</option>
<option value="Titanium">Titanium</option>
<option value="Titanium ASTM F136">Titanium ASTM F136</option>
<option value="Titanium 6AL4VELI ASTM F-136 implant grade">Titanium 6AL4VELI ASTM F-136 implant grade</option>
<option value="Titanium Ti-6Al-7Nb ASTM-F1295 implant grade">Titanium Ti-6Al-7Nb ASTM-F1295 implant grade</option>
<option value="PVD plated titanium">PVD plated titanium</option>
<option value="Color plated titanium">Color plated titanium</option>
<option value="Tungsten">Tungsten</option>
<option value="White brass">White brass</option>	
<option value="White metal">White metal</option>
</optgroup>
<optgroup label="GOLD">
<option value="Gold">Gold</option>
<option value="14K gold">14K gold</option>
<option value="18K gold">18K gold</option>
<option value="22K gold">22K gold</option>
<option value="24K gold">24K gold</option>
<option value="Solid Rose gold">Solid Rose gold</option>
<option value="Solid White gold">Solid White gold</option>
<option value="Solid Yellow gold">Solid Yellow gold</option>
<option value="Rose gold plated">Rose gold plated</option>
<option value="White gold plated">White gold plated</option>
<option value="Yellow gold plated">Yellow gold plated</option>
<option value="Platinum">Platinum</option>
<option value="Platinum plated">Platinum plated</option>
</optgroup>
<optgroup label="GLASS">
<option value="Glass">Glass</option>
<option value="Dichro">Dichro</option>
<option value="Fiber optic">Fiber optic</option>
<option value="Pyrex Glass">Pyrex Glass</option>
<option value="Quartz Glass">Quartz glass</option>
<option value="Soda-lime glass">Soda-lime glass</option>
</optgroup>
<optgroup label="ORGANICS">
<option value="Organic">Organic</option>
<option value="Amber">Amber</option>
<option value="Bamboo">Bamboo</option>
<option value="Bone">Bone</option>
<option value="Fossils">Fossils</option>
<option value="Fossilized bone">Fossilized bone</option>
<option value="Horn">Horn</option>
<option value="Jet">Jet</option>
<option value="Palm seed">Palm seed</option>
<option value="Shell">Shell</option>		
<option value="Stone">Stone</option>		
<option value="Vegan">Vegan</option>
</optgroup>
<optgroup label="WOODS">
<option value="Wood">Wood</option>
<option value="Amboyna burl">Amboyna burl</option>
<option value="Apricot">Apricot</option>
<option value="Arang">Arang</option>
<option value="Bloodwood">Bloodwood</option>
<option value="Chechen">Chechen</option>
<option value="Cherry">Cherry</option>
<option value="Coconut wood">Coconut wood</option>
<option value="Crocodile">Crocodile</option>
<option value="Ebony">Ebony</option>
<option value="Gentawas">Gentawas</option>
<option value="Granadillo">Granadillo</option>
<option value="Ironwood">Ironwood</option>
<option value="Jackfruit">Jackfruit</option>
<option value="Katalox">Katalox</option>
<option value="Lignum vitae">Lignum vitae</option>
<option value="Maple">Maple</option>
<option value="Olivewood">Olivewood</option>
<option value="Osage orange">Osage orange</option>
<option value="Palmwood">Palmwood</option>
<option value="Pear">Pear</option>
<option value="Pink ivory">Pink ivory</option>
<option value="Raintree">Raintree</option>
<option value="Saba">Saba</option>
<option value="Tamarind">Tamarind</option>
<option value="Tewel">Tewel</option>
<option value="Tiger ebony">Tiger ebony</option>
<option value="Verawood">Verawood</option>
<option value="Zebrawood">Zebrawood</option>
</optgroup>
<optgroup label="GEMS">
<option value="Synthetic gemstones">Synthetic gemstones</option>
<option value="Genuine gemstones">Genuine gemstones</option>
<option value="Synthetic pearl">Synthetic pearl</option>
<option value="Synthetic opals">Synthetic opals</option>
</optgroup>
</optgroup label="PLASTICS">
<option value="Acetate">Acetate</option>
<option value="Acrylic">Acrylic</option>
<option value="Bioplast">Bioplast</option>
<option value="Delrin">Delrin</option>
<option value="FDA approved acrylic">FDA approved acrylic</option>
<option value="Flexible Plastic">Flexible Plastic</option>
<option value="Latex">Latex</option>
<option value="PTFE">PTFE</option>
<option value="Resin">Resin</option>
<option value="Rubber">Rubber</option>
<option value="Silicone">Silicone</option>
</optgroup>
<optgroup label="MISC">
<option value="none - n/a">none</option>
<option value="Ceramic">Ceramic</option>
<option value="Cotton">Cotton</option>
<option value="Hemp">Hemp</option>
<option value="Leather">Leather</option>

