<option value="">&nbsp;</option>
<option value="Gold">Gold</option>
<option value="Glass">Glass</option>
<option value="Wood">Wood</option>

<option value="">&nbsp;</option>
<option value="">___ METALS ____________</option>
<option value="Brass">Brass</option>
<option value="Bronze">Bronze</option>
<option value="Ceramic plated">Ceramic plated</option>
<option value="Cobalt-Chrome">Cobalt-Chrome</option>
<option value="Copper">Copper</option>		
<option value="Niobium">Niobium</option>
<option value="Rhodium plated">Rhodium plated</option>
<option value="Yellow gold plated">Yellow gold plated</option>
<option value="Rose gold plated">Rose gold plated</option>
<option value="Sterling Silver">Sterling Silver</option>
<option value="Sterling Silver plated">Sterling Silver plated</option>
<option value="Platinum">Platinum</option>
<option value="Platinum plated">Platinum plated</option>
<option value="316L Stainless Steel">316L Stainless Steel</option>
<option value="316LVM ASTM F-138 Implant Grade Steel">316LVM ASTM F-138 Implant Grade Steel</option>
<option value="PVD plated">PVD plated</option>
<option value="PVD plated steel">PVD plated steel</option>
<option value="Color plated steel">Color plated steel</option>
<option value="Titanium">Titanium</option>
<option value="Titanium ASTM F136">Titanium ASTM F136</option>
<option value="Titanium 6AL4VELI ASTM F-136 implant grade">Titanium 6AL4VELI ASTM F-136 implant grade</option>
<option value="Titanium Ti-6Al-7Nb ASTM-F1295 implant grade">Titanium Ti-6Al-7Nb ASTM-F1295 implant grade</option>
<option value="PVD plated titanium">PVD plated titanium</option>
<option value="Color plated titanium">Color plated titanium</option>
<option value="Tungsten">Tungsten</option>
<option value="White brass">White brass</option>	
<option value="White metal">White metal</option>
<option value="">&nbsp;</option>
<option value="">&nbsp;</option>

<option value="">___ ORGANICS __________</option>
<option value="Amber">Amber</option>
<option value="Bamboo">Bamboo</option>
<option value="Bone">Bone</option>
<option value="Fossils">Fossils</option>
<option value="Fossilized bone">Fossilized bone</option>
<option value="Horn">Horn</option>
<option value="Jet">Jet</option>
<option value="Palm seed">Palm seed</option>
<option value="Shell">Shell</option>		
<option value="Stone">Stone</option>		
<option value="Vegan">Vegan</option>

<option value="">&nbsp;</option>
<option value="">___ PLASTICS ___________</option>
<option value="Acetate">Acetate</option>
<option value="Acrylic">Acrylic</option>
<option value="Bioplast">Bioplast</option>
<option value="Delrin">Delrin</option>
<option value="FDA approved acrylic">FDA approved acrylic</option>
<option value="Flexible Plastic">Flexible Plastic</option>
<option value="Latex">Latex</option>
<option value="PTFE">PTFE</option>
<option value="Rubber">Rubber</option>
<option value="Silicone">Silicone</option>

<option value="">&nbsp;</option>
<option value="">___ OTHER ___________</option>
<option value="Ceramic">Ceramic</option>
<option value="Cotton">Cotton</option>
<option value="Hemp">Hemp</option>
<option value="Leather">Leather</option>
<option value="Synthetic gemstones">Synthetic gemstones</option>