<option value="Length: ">Length: </option>
<option value="Diameter: ">Diameter: </option>
<option value="Ball size(s): ">Ball size(s): </option>
<option value="Disk size(s): ">Disk size(s): </option>
<option value="Color: ">Color: </option>
<option value="Titanium color(s): ">Titanium color(s): </option>
<option value="Niobium color(s): ">Niobium color(s): </option>
<option value="Gold color: ">Gold color: </option>
<option value="Gem color(s): ">Gem color(s): </option>	
<option value="Gem size(s): ">Gem size(s): </option>
<option value="Bezel size(s): ">Bezel size(s): </option>
<option value="Flare type: ">Flare type: </option>
<option value="Wearable: ">Wearable: </option>
<option value="Glass color(s): ">Glass color(s): </option>
<option value="Direction: ">Direction: </option>
<option value="Center: ">Center: </option>
<option value="Outer: ">Outer: </option>
<option value="Top: ">Top: </option>
<option value="Bottom: ">Bottom: </option>