<form class="form-inline" action="/admin/invoice.asp" method="post">
    <input class="form-control form-control" type="text" name="invoice_num" placeholder="Inovice #">
    <button class="btn btn-sm btn-secondary ml-2" type="submit">Search</button>
</form>
<form class="form-inline" action="/admin/order history.asp" method="get">
    <input class="form-control form-control" type="text" name="var_email" placeholder="E-mail">
    <button class="btn btn-sm btn-secondary ml-2" type="submit">Search</button>
</form>	
<form class="form-inline" name="/admin/website_search" method="get" action="order history.asp">
    <input class="form-control form-control mr-2" name="var_first" type="text" placeholder="First name" size="10">
    <input class="form-control form-control" name="var_last" type="text" placeholder="Last name" size="10" ><br>
    <button class="btn btn-sm btn-secondary mt-1" type="submit">Search</button>
</form>	