<form action="/admin/customer_search.asp" method="get">
						
    <input class="form-control form-control mb-2" name="first" type="text" placeholder="First name">
    
    <input class="form-control form-control mb-2" name="last" type="text" placeholder="Last name">
    
    <input class="form-control form-control mb-2" name="email" type="text" placeholder="E-mail">
        
    <input class="form-control form-control mb-2" name="CustomerID" type="text" placeholder="Customer #">
    <button class="btn btn-sm btn-secondary" type="submit">Search</button>
</form>