<form id="frm-error">
    Select item issue<br/>
    <select class="form-control form-control-sm mb-2" name="item_issue" id="item_issue">
      <option value="Print new scanning label">Print new scanning label</option>
      <option value="Wrong items in bin">Wrong items in bin</option>
      <option value="Broken item">Broken item</option>
      <option value="Quantity is off">Quantity is off</option>
      <option value="Combine bags">Combine bags</option>
      <option value="Needs to be paired">Needs to be paired</option>
      <option value="Singles are bad match">Singles are bad match</option>
      <option value="Needs new location">Needs new location</option>
    </select>
    Additional info (optional):<br/>
    <textarea class="form-control form-control-sm" id="error_description"></textarea>	  
    </form>