<h6 class="border-bottom border-secondary text-center">EMPLOYEE METRICS</h6>
<ul class="list-unstyled">
   
<li>
    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Product listing"  data-report-url="reportEmbed?reportId=4edddc05-dcb3-4761-b5b3-14c8ce0c19df&pageName=ReportSection781f072d6b16235e5969">
        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
        Product listing
        </a>
</li>
<li>
    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Jewelry & photo reviews"  data-report-url="reportEmbed?reportId=4edddc05-dcb3-4761-b5b3-14c8ce0c19df&pageName=ReportSectione1193b6f7efac16f4022">
        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
        Jewelry & photo reviews
        </a>
</li>
<li>
    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Returns processed"  data-report-url="reportEmbed?reportId=4edddc05-dcb3-4761-b5b3-14c8ce0c19df&pageName=ReportSection1f8ef7fcee613c042043">
        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
        Returns processed
        </a>
</li>
<li>
    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Reships & problem orders processed"  data-report-url="reportEmbed?reportId=4edddc05-dcb3-4761-b5b3-14c8ce0c19df&pageName=ReportSection2d18d02abc53bdfb7904">
        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
        Reships & problem orders processed
        </a>
</li>
<li>
    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="FB / Instagram orders"  data-report-url="reportEmbed?reportId=4edddc05-dcb3-4761-b5b3-14c8ce0c19df&pageName=ReportSection8e201567a226e36102ee">
        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
        FB / Instagram orders
        </a>
</li>
<li>
    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Tagged products to restock"  data-report-url="reportEmbed?reportId=4edddc05-dcb3-4761-b5b3-14c8ce0c19df&pageName=ReportSectionb8caf000069acaa9ca9c">
        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
        Tagged products to restock
        </a>
</li>
    
</ul>