<h6 class="border-bottom border-secondary text-center">PACKING DEPARTMENT</h6>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="/admin/packing-errors.asp"><i class="fa fa-angle-right mr-2 ml-2"></i>&nbsp;Packer errors</a>
                                </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Orders Overview"  data-report-url="reportEmbed?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSection" >
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Orders overview
                                </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Packing Stats"  data-report-url="reportEmbed?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSectionecb8bec0b16576690ac1" >
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Packing stats
                                </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Pulling Stats"  data-report-url="reportEmbed?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSection0cf58b6cd80c063e308a" >
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Pulling stats
                                </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Items Stats"  data-report-url="reportEmbed?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSectiona5059775a4468f737145" >
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Items stats
                                </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Product Restocks"  data-report-url="reportEmbed?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSectionb09c04b6b8ae803d9e39">
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Product restocks
                                </a>
                            </li>
                                
                            </ul>