<h6 class="border-bottom border-secondary text-center">E-COMMERCE ANALYTICS</h6>
<ul class="list-unstyled">
  
    <li>
        <a href="https://datastudio.google.com/u/0/reporting/b0e4b497-15a9-491d-9134-6eaab615d3a6/page/5auqB" target="_blank">
            <img class="mr-1" src="/images/icons/google-data-studio.png" height="20px">
            Conversion rate & sales funnel measurements
            </a>
    </li>
    <li>
        <a href="https://datastudio.google.com/u/0/reporting/1867a52b-504b-46ca-aa08-dcd6ae458f32/page/6zXD" target="_blank">
            <img class="mr-1" src="/images/icons/google-data-studio.png" height="20px">
            Search traffic monitoring dashboard
            </a>
    </li>
    <li>
        <a href="https://datastudio.google.com/u/0/reporting/d6907d3d-5c6d-4e90-bab5-3d436453d1e7/page/xFbeC" target="_blank">
            <img class="mr-1" src="/images/icons/google-data-studio.png" height="20px">
            Search words bubble chart
            </a>
    </li>
    <li>
        <a href="/admin/competitor-research.asp" >
            <img class="mr-1" src="/images/icons/google-trends.png" height="20px">
            Competitor popularity trends
            </a>
    </li>
</ul>