<h6 class="border-bottom border-secondary text-center">CUSTOMERS</h6>
                            <ul class="list-unstyled">
                            <li>
                                    <a href="/admin/power-bi/reports.asp?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSection4e2b66748b878ba09802&reportName=Sales by customer">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Sales by customer
                                        </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Customer counts"  data-report-url="reportEmbed?reportId=1fbf5d3f-a940-4fbc-83c2-9b8140e3312c&pageName=ReportSectionc9486765338688687030">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Customer counts
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Account creation"  data-report-url="reportEmbed?reportId=1fbf5d3f-a940-4fbc-83c2-9b8140e3312c&pageName=ReportSectionc281d354339d98c1dda8">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Account creation
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Survey replies"  data-report-url="reportEmbed?reportId=1fbf5d3f-a940-4fbc-83c2-9b8140e3312c&pageName=ReportSection">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Survey replies
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Saved searches use"  data-report-url="reportEmbed?reportId=1fbf5d3f-a940-4fbc-83c2-9b8140e3312c&pageName=ReportSectionb93429d7140cc297392e">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Saved searches use
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Registrations & newsletters"  data-report-url="reportEmbed?reportId=2fe435c0-68e7-4698-bbf9-9fa6925746e9&pageName=ReportSection5897cea55cb9f1bdb43f">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Registrations & newsletters
                                    </a>
                            </li>
                            </ul>