<h6 class="border-bottom border-secondary text-center">POTENTIAL REVENUE</h6>
                            <ul class="list-unstyled">
                                
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Abandoned carts"  data-report-url="reportEmbed?reportId=2fe435c0-68e7-4698-bbf9-9fa6925746e9&pageName=ReportSection8da612ddfee8cd25cd84">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Abandoned carts
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Abandoned carts funnel"  data-report-url="reportEmbed?reportId=2fe435c0-68e7-4698-bbf9-9fa6925746e9&pageName=ReportSectiond4e6bafcae3e7bd89b9c">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Abandoned carts funnel
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Daily abandoned carts"  data-report-url="reportEmbed?reportId=2fe435c0-68e7-4698-bbf9-9fa6925746e9&pageName=ReportSectionebec3316370647bd9e02">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Daily abandoned carts
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Wishlist potential revenue"  data-report-url="reportEmbed?reportId=2fe435c0-68e7-4698-bbf9-9fa6925746e9&pageName=ReportSection94178c9682b7e127a75d">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Wishlist potential revenue
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Save for later potential revenue"  data-report-url="reportEmbed?reportId=2fe435c0-68e7-4698-bbf9-9fa6925746e9&pageName=ReportSectionac38b93470d606e28ed3">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Save for later potential revenue
                                    </a>
                            </li>
                                
                            </ul>