<h6 class="border-bottom border-secondary text-center">E-COMMERCE ANALYTICS</h6>
<ul class="list-unstyled">
  
    <li>
        <a href="https://datastudio.google.com/u/0/reporting/b0e4b497-15a9-491d-9134-6eaab615d3a6/page/5auqB" target="_blank">
            <img class="mr-1" src="/images/icons/google-data-studio.png" height="20px">
            Google dashboard
            </a>
    </li>
    <li>
        <a href="/admin/competitor-research.asp" >
            <img class="mr-1" src="/images/icons/google-trends.png" height="20px">
            Competitor trends
            </a>
    </li>
</ul>