<h6 class="border-bottom border-secondary text-center ">INVENTORY</h6>
                            <ul class="list-unstyled">
                              <li>
                                    <a href="/admin/power-bi/reports.asp?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection42de71d8c6805a9cd981&reportName=Inventory Overview" target="_blank">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Inventory Overview
                                        </a>
                            </li>
 <h6 class="mt-3 border-bottom border-secondary text-center">WHOLESALE & REVENUE</h6>
                            <li>
                                    <a href="/admin/power-bi/reports.asp?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection781f072d6b16235e5969&reportName=Incoming versus Outgoing" target="_blank">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Incoming vs outgoing
                                        </a>
                            </li>
                            <li>
                                <a href="/admin/power-bi/reports.asp?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSectionc8d3d89f753886d9893b&reportName=Wholesale movement" target="_blank">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Wholesale outgoing $ by vendor
                                    </a>
                            </li>
                            <li>
                                <a href="/admin/power-bi/reports.asp?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSectionbddd7e9b0e965ec3d95e&reportName=Wholesale stock on hand" target="_blank">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Wholesale value by vendor
                                    </a>
                            </li>
 <h6 class="mt-3 border-bottom border-secondary text-center">VENDORS</h6>
                            <li>
                                <a href="/admin/power-bi/reports.asp?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection40f4fdae8ccf16fc0e2b&reportName=Vendor profits" target="_blank">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Vendor profits
                                    </a>
                            </li>
 <h6 class="mt-3 border-bottom border-secondary text-center">PRODUCTS</h6>
                              <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Product Performance (90 Days)"  data-report-url="reportEmbed?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection9108874d3b3d071b1106">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Product Performance (90 Days)
                                    </a>
                            </li>
                                                        <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Top selling products"  data-report-url="reportEmbed?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection60e33d96a371a3a00de0">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Top selling products
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Inactive items with qty"  data-report-url="reportEmbed?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSectionc36c32481ac846171df1">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Inactive items with qty
                                    </a>
                            </li>

                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Top gauges"  data-report-url="reportEmbed?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection2dabdc6b693ab8a0b22e">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Top gauges
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Backorders"  data-report-url="reportEmbed?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSectiondb3e6db04e1c0fb1b26b">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Backorders
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Items rated below 4 stars"  data-report-url="reportEmbed?reportId=b1b71c73-5ea7-41b6-98e7-0f6f18d8bd51&pageName=ReportSection0995471f3d43f1ec43b7">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Items rated below 4 stars
                                    </a>
                            </li>
                            </ul>