<h6 class="border-bottom border-secondary text-center">SALES</h6>
                            <ul class="list-unstyled">
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Orders & sales overview"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSection">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Orders & sales overview
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Shipping revenue"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSectionba4ce75b01d27f9f9abe">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Shipping revenue
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Payment methods"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSectionc3293043a32b093a128c">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                   Payment methods
                                    </a>
                            </li>

                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Anodizing revenue"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSection8f49a326e363c433e68c">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Anodizing revenue
                                        </a>

                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Gift certificates"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSection3dbd565056bc0038ac64">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Gift certificates
                                        </a>
                                </li>
                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Free items"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSection7c15a4140d6f6facd1cf">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Free items
                                        </a>
                                </li>
                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Return losses"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSectioncc6939f9391d81c1ebf7">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Return losses
                                        </a>
                                </li>
                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Taxes collected"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSection57a2d0fa08566a3cb9b7">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Taxes collected
                                        </a>
                                </li>
                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="USA sales"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSectionccdec22c60ecc98573e0">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        USA sales
                                        </a>
                                </li>
                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="International sales"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSectionb60b615e8ed65b97cd82">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        International sales
                                        </a>
                                </li>

                            </ul>