<h6 class="border-bottom border-secondary text-center">CUSTOM ORDERS</h6>
                            <ul class="list-unstyled">
                              
                                <li>
                                    <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Custom orders revenue"  data-report-url="reportEmbed?reportId=c88f768b-44f2-4394-8802-2577a5ef3cdf&pageName=ReportSectionc4da01ec413cf108a641">
                                        <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                        Custom orders revenue
                                        </a>
                                </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Shipping status issues"  data-report-url="reportEmbed?reportId=e1acf509-fb33-4f12-937a-f23c0829fdf1&pageName=ReportSection">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    Shipping status issues
                                    </a>
                            </li>
                            <li>
                                <a href="" class="load-report" data-toggle="modal" data-target="#modal-reports" data-report-title="Custom orders with anodizing"  data-report-url="reportEmbed?reportId=e1acf509-fb33-4f12-937a-f23c0829fdf1&pageName=ReportSectionc65c7a14c8c54d39bab7">
                                    <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                    w/ Anodizing
                                    </a>
                            </li>
                               
                            </ul>