<h6 class="border-bottom border-secondary text-center">PACKING DEPARTMENT</h6>
                            <ul class="list-unstyled">
                                <li>
                                    <a href="/admin/packing-errors.asp"><i class="fa fa-angle-right mr-2 ml-2"></i>&nbsp;Packer errors</a>
                                </li>
                            <li>
                                <a href="/admin/power-bi/reports.asp?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSection&reportName=Orders overview" >
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Orders overview
                                </a>
                            </li>
                            <li>
                                <a href="/admin/power-bi/reports.asp?reportId=15766e9d-3dcc-415f-9d97-f4e9c66fb5e8&pageName=ReportSectionecb8bec0b16576690ac1&reportName=Packing room stats" >
                                <img class="mr-1" src="/images/icons/power-bi.png" height="20px">
                                Packing room stats
                                </a>
                            </li>                               
                            </ul>