<%
Function getContentTypeFromFileName(filename)
	extension = Mid(fileName, InstrRev(fileName, "."))
	Select case extension
		Case ".323"
			getContentTypeFromFileName="text/h323"
		Case ".3g2"
			getContentTypeFromFileName="video/3gpp2"
		Case ".3gp"
			getContentTypeFromFileName="video/3gpp"
		Case ".3gp2"
			getContentTypeFromFileName="video/3gpp2"
		Case ".3gpp"
			getContentTypeFromFileName="video/3gpp"
		Case ".7z"
			getContentTypeFromFileName="application/x-7z-compressed"
		Case ".aa"
			getContentTypeFromFileName="audio/audible"
		Case ".AAC"
			getContentTypeFromFileName="audio/aac"
		Case ".aaf"
			getContentTypeFromFileName="application/octet-stream"
		Case ".aax"
			getContentTypeFromFileName="audio/vnd.audible.aax"
		Case ".ac3"
			getContentTypeFromFileName="audio/ac3"
		Case ".aca"
			getContentTypeFromFileName="application/octet-stream"
		Case ".accda"
			getContentTypeFromFileName="application/msaccess.addin"
		Case ".accdb"
			getContentTypeFromFileName="application/msaccess"
		Case ".accdc"
			getContentTypeFromFileName="application/msaccess.cab"
		Case ".accde"
			getContentTypeFromFileName="application/msaccess"
		Case ".accdr"
			getContentTypeFromFileName="application/msaccess.runtime"
		Case ".accdt"
			getContentTypeFromFileName="application/msaccess"
		Case ".accdw"
			getContentTypeFromFileName="application/msaccess.webapplication"
		Case ".accft"
			getContentTypeFromFileName="application/msaccess.ftemplate"
		Case ".acx"
			getContentTypeFromFileName="application/internet-property-stream"
		Case ".AddIn"
			getContentTypeFromFileName="text/xml"
		Case ".ade"
			getContentTypeFromFileName="application/msaccess"
		Case ".adobebridge"
			getContentTypeFromFileName="application/x-bridge-url"
		Case ".adp"
			getContentTypeFromFileName="application/msaccess"
		Case ".ADT"
			getContentTypeFromFileName="audio/vnd.dlna.adts"
		Case ".ADTS"
			getContentTypeFromFileName="audio/aac"
		Case ".afm"
			getContentTypeFromFileName="application/octet-stream"
		Case ".ai"
			getContentTypeFromFileName="application/postscript"
		Case ".aif"
			getContentTypeFromFileName="audio/x-aiff"
		Case ".aifc"
			getContentTypeFromFileName="audio/aiff"
		Case ".aiff"
			getContentTypeFromFileName="audio/aiff"
		Case ".air"
			getContentTypeFromFileName="application/vnd.adobe.air-application-installer-package+zip"
		Case ".amc"
			getContentTypeFromFileName="application/x-mpeg"
		Case ".application"
			getContentTypeFromFileName="application/x-ms-application"
		Case ".art"
			getContentTypeFromFileName="image/x-jg"
		Case ".asa"
			getContentTypeFromFileName="application/xml"
		Case ".asax"
			getContentTypeFromFileName="application/xml"
		Case ".ascx"
			getContentTypeFromFileName="application/xml"
		Case ".asd"
			getContentTypeFromFileName="application/octet-stream"
		Case ".asf"
			getContentTypeFromFileName="video/x-ms-asf"
		Case ".ashx"
			getContentTypeFromFileName="application/xml"
		Case ".asi"
			getContentTypeFromFileName="application/octet-stream"
		Case ".asm"
			getContentTypeFromFileName="text/plain"
		Case ".asmx"
			getContentTypeFromFileName="application/xml"
		Case ".aspx"
			getContentTypeFromFileName="application/xml"
		Case ".asr"
			getContentTypeFromFileName="video/x-ms-asf"
		Case ".asx"
			getContentTypeFromFileName="video/x-ms-asf"
		Case ".atom"
			getContentTypeFromFileName="application/atom+xml"
		Case ".au"
			getContentTypeFromFileName="audio/basic"
		Case ".avi"
			getContentTypeFromFileName="video/x-msvideo"
		Case ".axs"
			getContentTypeFromFileName="application/olescript"
		Case ".bas"
			getContentTypeFromFileName="text/plain"
		Case ".bcpio"
			getContentTypeFromFileName="application/x-bcpio"
		Case ".bin"
			getContentTypeFromFileName="application/octet-stream"
		Case ".bmp"
			getContentTypeFromFileName="image/bmp"
		Case ".c"
			getContentTypeFromFileName="text/plain"
		Case ".cab"
			getContentTypeFromFileName="application/octet-stream"
		Case ".caf"
			getContentTypeFromFileName="audio/x-caf"
		Case ".calx"
			getContentTypeFromFileName="application/vnd.ms-office.calx"
		Case ".cat"
			getContentTypeFromFileName="application/vnd.ms-pki.seccat"
		Case ".cc"
			getContentTypeFromFileName="text/plain"
		Case ".cd"
			getContentTypeFromFileName="text/plain"
		Case ".cdda"
			getContentTypeFromFileName="audio/aiff"
		Case ".cdf"
			getContentTypeFromFileName="application/x-cdf"
		Case ".cer"
			getContentTypeFromFileName="application/x-x509-ca-cert"
		Case ".chm"
			getContentTypeFromFileName="application/octet-stream"
		Case ".class"
			getContentTypeFromFileName="application/x-java-applet"
		Case ".clp"
			getContentTypeFromFileName="application/x-msclip"
		Case ".cmx"
			getContentTypeFromFileName="image/x-cmx"
		Case ".cnf"
			getContentTypeFromFileName="text/plain"
		Case ".cod"
			getContentTypeFromFileName="image/cis-cod"
		Case ".config"
			getContentTypeFromFileName="application/xml"
		Case ".contact"
			getContentTypeFromFileName="text/x-ms-contact"
		Case ".coverage"
			getContentTypeFromFileName="application/xml"
		Case ".cpio"
			getContentTypeFromFileName="application/x-cpio"
		Case ".cpp"
			getContentTypeFromFileName="text/plain"
		Case ".crd"
			getContentTypeFromFileName="application/x-mscardfile"
		Case ".crl"
			getContentTypeFromFileName="application/pkix-crl"
		Case ".crt"
			getContentTypeFromFileName="application/x-x509-ca-cert"
		Case ".cs"
			getContentTypeFromFileName="text/plain"
		Case ".csdproj"
			getContentTypeFromFileName="text/plain"
		Case ".csh"
			getContentTypeFromFileName="application/x-csh"
		Case ".csproj"
			getContentTypeFromFileName="text/plain"
		Case ".css"
			getContentTypeFromFileName="text/css"
		Case ".csv"
			getContentTypeFromFileName="text/csv"
		Case ".cur"
			getContentTypeFromFileName="application/octet-stream"
		Case ".cxx"
			getContentTypeFromFileName="text/plain"
		Case ".dat"
			getContentTypeFromFileName="application/octet-stream"
		Case ".datasource"
			getContentTypeFromFileName="application/xml"
		Case ".dbproj"
			getContentTypeFromFileName="text/plain"
		Case ".dcr"
			getContentTypeFromFileName="application/x-director"
		Case ".def"
			getContentTypeFromFileName="text/plain"
		Case ".deploy"
			getContentTypeFromFileName="application/octet-stream"
		Case ".der"
			getContentTypeFromFileName="application/x-x509-ca-cert"
		Case ".dgml"
			getContentTypeFromFileName="application/xml"
		Case ".dib"
			getContentTypeFromFileName="image/bmp"
		Case ".dif"
			getContentTypeFromFileName="video/x-dv"
		Case ".dir"
			getContentTypeFromFileName="application/x-director"
		Case ".disco"
			getContentTypeFromFileName="text/xml"
		Case ".dll"
			getContentTypeFromFileName="application/x-msdownload"
		Case ".dll.config"
			getContentTypeFromFileName="text/xml"
		Case ".dlm"
			getContentTypeFromFileName="text/dlm"
		Case ".doc"
			getContentTypeFromFileName="application/msword"
		Case ".docm"
			getContentTypeFromFileName="application/vnd.ms-word.document.macroEnabled.12"
		Case ".docx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.wordprocessingml.document"
		Case ".dot"
			getContentTypeFromFileName="application/msword"
		Case ".dotm"
			getContentTypeFromFileName="application/vnd.ms-word.template.macroEnabled.12"
		Case ".dotx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.wordprocessingml.template"
		Case ".dsp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".dsw"
			getContentTypeFromFileName="text/plain"
		Case ".dtd"
			getContentTypeFromFileName="text/xml"
		Case ".dtsConfig"
			getContentTypeFromFileName="text/xml"
		Case ".dv"
			getContentTypeFromFileName="video/x-dv"
		Case ".dvi"
			getContentTypeFromFileName="application/x-dvi"
		Case ".dwf"
			getContentTypeFromFileName="drawing/x-dwf"
		Case ".dwp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".dxr"
			getContentTypeFromFileName="application/x-director"
		Case ".eml"
			getContentTypeFromFileName="message/rfc822"
		Case ".emz"
			getContentTypeFromFileName="application/octet-stream"
		Case ".eot"
			getContentTypeFromFileName="application/octet-stream"
		Case ".eps"
			getContentTypeFromFileName="application/postscript"
		Case ".etl"
			getContentTypeFromFileName="application/etl"
		Case ".etx"
			getContentTypeFromFileName="text/x-setext"
		Case ".evy"
			getContentTypeFromFileName="application/envoy"
		Case ".exe"
			getContentTypeFromFileName="application/octet-stream"
		Case ".exe.config"
			getContentTypeFromFileName="text/xml"
		Case ".fdf"
			getContentTypeFromFileName="application/vnd.fdf"
		Case ".fif"
			getContentTypeFromFileName="application/fractals"
		Case ".filters"
			getContentTypeFromFileName="Application/xml"
		Case ".fla"
			getContentTypeFromFileName="application/octet-stream"
		Case ".flr"
			getContentTypeFromFileName="x-world/x-vrml"
		Case ".flv"
			getContentTypeFromFileName="video/x-flv"
		Case ".fsscript"
			getContentTypeFromFileName="application/fsharp-script"
		Case ".fsx"
			getContentTypeFromFileName="application/fsharp-script"
		Case ".generictest"
			getContentTypeFromFileName="application/xml"
		Case ".gif"
			getContentTypeFromFileName="image/gif"
		Case ".group"
			getContentTypeFromFileName="text/x-ms-group"
		Case ".gsm"
			getContentTypeFromFileName="audio/x-gsm"
		Case ".gtar"
			getContentTypeFromFileName="application/x-gtar"
		Case ".gz"
			getContentTypeFromFileName="application/x-gzip"
		Case ".h"
			getContentTypeFromFileName="text/plain"
		Case ".hdf"
			getContentTypeFromFileName="application/x-hdf"
		Case ".hdml"
			getContentTypeFromFileName="text/x-hdml"
		Case ".hhc"
			getContentTypeFromFileName="application/x-oleobject"
		Case ".hhk"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hhp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hlp"
			getContentTypeFromFileName="application/winhlp"
		Case ".hpp"
			getContentTypeFromFileName="text/plain"
		Case ".hqx"
			getContentTypeFromFileName="application/mac-binhex40"
		Case ".hta"
			getContentTypeFromFileName="application/hta"
		Case ".htc"
			getContentTypeFromFileName="text/x-component"
		Case ".htm"
			getContentTypeFromFileName="text/html"
		Case ".html"
			getContentTypeFromFileName="text/html"
		Case ".htt"
			getContentTypeFromFileName="text/webviewhtml"
		Case ".hxa"
			getContentTypeFromFileName="application/xml"
		Case ".hxc"
			getContentTypeFromFileName="application/xml"
		Case ".hxd"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxe"
			getContentTypeFromFileName="application/xml"
		Case ".hxf"
			getContentTypeFromFileName="application/xml"
		Case ".hxh"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxi"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxk"
			getContentTypeFromFileName="application/xml"
		Case ".hxq"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxr"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxs"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxt"
			getContentTypeFromFileName="text/html"
		Case ".hxv"
			getContentTypeFromFileName="application/xml"
		Case ".hxw"
			getContentTypeFromFileName="application/octet-stream"
		Case ".hxx"
			getContentTypeFromFileName="text/plain"
		Case ".i"
			getContentTypeFromFileName="text/plain"
		Case ".ico"
			getContentTypeFromFileName="image/x-icon"
		Case ".ics"
			getContentTypeFromFileName="application/octet-stream"
		Case ".idl"
			getContentTypeFromFileName="text/plain"
		Case ".ief"
			getContentTypeFromFileName="image/ief"
		Case ".iii"
			getContentTypeFromFileName="application/x-iphone"
		Case ".inc"
			getContentTypeFromFileName="text/plain"
		Case ".inf"
			getContentTypeFromFileName="application/octet-stream"
		Case ".inl"
			getContentTypeFromFileName="text/plain"
		Case ".ins"
			getContentTypeFromFileName="application/x-internet-signup"
		Case ".ipa"
			getContentTypeFromFileName="application/x-itunes-ipa"
		Case ".ipg"
			getContentTypeFromFileName="application/x-itunes-ipg"
		Case ".ipproj"
			getContentTypeFromFileName="text/plain"
		Case ".ipsw"
			getContentTypeFromFileName="application/x-itunes-ipsw"
		Case ".iqy"
			getContentTypeFromFileName="text/x-ms-iqy"
		Case ".isp"
			getContentTypeFromFileName="application/x-internet-signup"
		Case ".ite"
			getContentTypeFromFileName="application/x-itunes-ite"
		Case ".itlp"
			getContentTypeFromFileName="application/x-itunes-itlp"
		Case ".itms"
			getContentTypeFromFileName="application/x-itunes-itms"
		Case ".itpc"
			getContentTypeFromFileName="application/x-itunes-itpc"
		Case ".IVF"
			getContentTypeFromFileName="video/x-ivf"
		Case ".jar"
			getContentTypeFromFileName="application/java-archive"
		Case ".java"
			getContentTypeFromFileName="application/octet-stream"
		Case ".jck"
			getContentTypeFromFileName="application/liquidmotion"
		Case ".jcz"
			getContentTypeFromFileName="application/liquidmotion"
		Case ".jfif"
			getContentTypeFromFileName="image/pjpeg"
		Case ".jnlp"
			getContentTypeFromFileName="application/x-java-jnlp-file"
		Case ".jpb"
			getContentTypeFromFileName="application/octet-stream"
		Case ".jpe"
			getContentTypeFromFileName="image/jpeg"
		Case ".jpeg"
			getContentTypeFromFileName="image/jpeg"
		Case ".jpg"
			getContentTypeFromFileName="image/jpeg"
		Case ".js"
			getContentTypeFromFileName="application/x-javascript"
		Case ".json"
			getContentTypeFromFileName="application/json"
		Case ".jsx"
			getContentTypeFromFileName="text/jscript"
		Case ".jsxbin"
			getContentTypeFromFileName="text/plain"
		Case ".latex"
			getContentTypeFromFileName="application/x-latex"
		Case ".library-ms"
			getContentTypeFromFileName="application/windows-library+xml"
		Case ".lit"
			getContentTypeFromFileName="application/x-ms-reader"
		Case ".loadtest"
			getContentTypeFromFileName="application/xml"
		Case ".lpk"
			getContentTypeFromFileName="application/octet-stream"
		Case ".lsf"
			getContentTypeFromFileName="video/x-la-asf"
		Case ".lst"
			getContentTypeFromFileName="text/plain"
		Case ".lsx"
			getContentTypeFromFileName="video/x-la-asf"
		Case ".lzh"
			getContentTypeFromFileName="application/octet-stream"
		Case ".m13"
			getContentTypeFromFileName="application/x-msmediaview"
		Case ".m14"
			getContentTypeFromFileName="application/x-msmediaview"
		Case ".m1v"
			getContentTypeFromFileName="video/mpeg"
		Case ".m2t"
			getContentTypeFromFileName="video/vnd.dlna.mpeg-tts"
		Case ".m2ts"
			getContentTypeFromFileName="video/vnd.dlna.mpeg-tts"
		Case ".m2v"
			getContentTypeFromFileName="video/mpeg"
		Case ".m3u"
			getContentTypeFromFileName="audio/x-mpegurl"
		Case ".m3u8"
			getContentTypeFromFileName="audio/x-mpegurl"
		Case ".m4a"
			getContentTypeFromFileName="audio/m4a"
		Case ".m4b"
			getContentTypeFromFileName="audio/m4b"
		Case ".m4p"
			getContentTypeFromFileName="audio/m4p"
		Case ".m4r"
			getContentTypeFromFileName="audio/x-m4r"
		Case ".m4v"
			getContentTypeFromFileName="video/x-m4v"
		Case ".mac"
			getContentTypeFromFileName="image/x-macpaint"
		Case ".mak"
			getContentTypeFromFileName="text/plain"
		Case ".man"
			getContentTypeFromFileName="application/x-troff-man"
		Case ".manifest"
			getContentTypeFromFileName="application/x-ms-manifest"
		Case ".map"
			getContentTypeFromFileName="text/plain"
		Case ".master"
			getContentTypeFromFileName="application/xml"
		Case ".mda"
			getContentTypeFromFileName="application/msaccess"
		Case ".mdb"
			getContentTypeFromFileName="application/x-msaccess"
		Case ".mde"
			getContentTypeFromFileName="application/msaccess"
		Case ".mdp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".me"
			getContentTypeFromFileName="application/x-troff-me"
		Case ".mfp"
			getContentTypeFromFileName="application/x-shockwave-flash"
		Case ".mht"
			getContentTypeFromFileName="message/rfc822"
		Case ".mhtml"
			getContentTypeFromFileName="message/rfc822"
		Case ".mid"
			getContentTypeFromFileName="audio/mid"
		Case ".midi"
			getContentTypeFromFileName="audio/mid"
		Case ".mix"
			getContentTypeFromFileName="application/octet-stream"
		Case ".mk"
			getContentTypeFromFileName="text/plain"
		Case ".mmf"
			getContentTypeFromFileName="application/x-smaf"
		Case ".mno"
			getContentTypeFromFileName="text/xml"
		Case ".mny"
			getContentTypeFromFileName="application/x-msmoney"
		Case ".mod"
			getContentTypeFromFileName="video/mpeg"
		Case ".mov"
			getContentTypeFromFileName="video/quicktime"
		Case ".movie"
			getContentTypeFromFileName="video/x-sgi-movie"
		Case ".mp2"
			getContentTypeFromFileName="video/mpeg"
		Case ".mp2v"
			getContentTypeFromFileName="video/mpeg"
		Case ".mp3"
			getContentTypeFromFileName="audio/mpeg"
		Case ".mp4"
			getContentTypeFromFileName="video/mp4"
		Case ".mp4v"
			getContentTypeFromFileName="video/mp4"
		Case ".mpa"
			getContentTypeFromFileName="video/mpeg"
		Case ".mpe"
			getContentTypeFromFileName="video/mpeg"
		Case ".mpeg"
			getContentTypeFromFileName="video/mpeg"
		Case ".mpf"
			getContentTypeFromFileName="application/vnd.ms-mediapackage"
		Case ".mpg"
			getContentTypeFromFileName="video/mpeg"
		Case ".mpp"
			getContentTypeFromFileName="application/vnd.ms-project"
		Case ".mpv2"
			getContentTypeFromFileName="video/mpeg"
		Case ".mqv"
			getContentTypeFromFileName="video/quicktime"
		Case ".ms"
			getContentTypeFromFileName="application/x-troff-ms"
		Case ".msi"
			getContentTypeFromFileName="application/octet-stream"
		Case ".mso"
			getContentTypeFromFileName="application/octet-stream"
		Case ".mts"
			getContentTypeFromFileName="video/vnd.dlna.mpeg-tts"
		Case ".mtx"
			getContentTypeFromFileName="application/xml"
		Case ".mvb"
			getContentTypeFromFileName="application/x-msmediaview"
		Case ".mvc"
			getContentTypeFromFileName="application/x-miva-compiled"
		Case ".mxp"
			getContentTypeFromFileName="application/x-mmxp"
		Case ".nc"
			getContentTypeFromFileName="application/x-netcdf"
		Case ".nsc"
			getContentTypeFromFileName="video/x-ms-asf"
		Case ".nws"
			getContentTypeFromFileName="message/rfc822"
		Case ".ocx"
			getContentTypeFromFileName="application/octet-stream"
		Case ".oda"
			getContentTypeFromFileName="application/oda"
		Case ".odc"
			getContentTypeFromFileName="text/x-ms-odc"
		Case ".odh"
			getContentTypeFromFileName="text/plain"
		Case ".odl"
			getContentTypeFromFileName="text/plain"
		Case ".odp"
			getContentTypeFromFileName="application/vnd.oasis.opendocument.presentation"
		Case ".ods"
			getContentTypeFromFileName="application/oleobject"
		Case ".odt"
			getContentTypeFromFileName="application/vnd.oasis.opendocument.text"
		Case ".one"
			getContentTypeFromFileName="application/onenote"
		Case ".onea"
			getContentTypeFromFileName="application/onenote"
		Case ".onepkg"
			getContentTypeFromFileName="application/onenote"
		Case ".onetmp"
			getContentTypeFromFileName="application/onenote"
		Case ".onetoc"
			getContentTypeFromFileName="application/onenote"
		Case ".onetoc2"
			getContentTypeFromFileName="application/onenote"
		Case ".orderedtest"
			getContentTypeFromFileName="application/xml"
		Case ".osdx"
			getContentTypeFromFileName="application/opensearchdescription+xml"
		Case ".p10"
			getContentTypeFromFileName="application/pkcs10"
		Case ".p12"
			getContentTypeFromFileName="application/x-pkcs12"
		Case ".p7b"
			getContentTypeFromFileName="application/x-pkcs7-certificates"
		Case ".p7c"
			getContentTypeFromFileName="application/pkcs7-mime"
		Case ".p7m"
			getContentTypeFromFileName="application/pkcs7-mime"
		Case ".p7r"
			getContentTypeFromFileName="application/x-pkcs7-certreqresp"
		Case ".p7s"
			getContentTypeFromFileName="application/pkcs7-signature"
		Case ".pbm"
			getContentTypeFromFileName="image/x-portable-bitmap"
		Case ".pcast"
			getContentTypeFromFileName="application/x-podcast"
		Case ".pct"
			getContentTypeFromFileName="image/pict"
		Case ".pcx"
			getContentTypeFromFileName="application/octet-stream"
		Case ".pcz"
			getContentTypeFromFileName="application/octet-stream"
		Case ".pdf"
			getContentTypeFromFileName="application/pdf"
		Case ".pfb"
			getContentTypeFromFileName="application/octet-stream"
		Case ".pfm"
			getContentTypeFromFileName="application/octet-stream"
		Case ".pfx"
			getContentTypeFromFileName="application/x-pkcs12"
		Case ".pgm"
			getContentTypeFromFileName="image/x-portable-graymap"
		Case ".pic"
			getContentTypeFromFileName="image/pict"
		Case ".pict"
			getContentTypeFromFileName="image/pict"
		Case ".pkgdef"
			getContentTypeFromFileName="text/plain"
		Case ".pkgundef"
			getContentTypeFromFileName="text/plain"
		Case ".pko"
			getContentTypeFromFileName="application/vnd.ms-pki.pko"
		Case ".pls"
			getContentTypeFromFileName="audio/scpls"
		Case ".pma"
			getContentTypeFromFileName="application/x-perfmon"
		Case ".pmc"
			getContentTypeFromFileName="application/x-perfmon"
		Case ".pml"
			getContentTypeFromFileName="application/x-perfmon"
		Case ".pmr"
			getContentTypeFromFileName="application/x-perfmon"
		Case ".pmw"
			getContentTypeFromFileName="application/x-perfmon"
		Case ".png"
			getContentTypeFromFileName="image/png"
		Case ".pnm"
			getContentTypeFromFileName="image/x-portable-anymap"
		Case ".pnt"
			getContentTypeFromFileName="image/x-macpaint"
		Case ".pntg"
			getContentTypeFromFileName="image/x-macpaint"
		Case ".pnz"
			getContentTypeFromFileName="image/png"
		Case ".pot"
			getContentTypeFromFileName="application/vnd.ms-powerpoint"
		Case ".potm"
			getContentTypeFromFileName="application/vnd.ms-powerpoint.template.macroEnabled.12"
		Case ".potx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.presentationml.template"
		Case ".ppa"
			getContentTypeFromFileName="application/vnd.ms-powerpoint"
		Case ".ppam"
			getContentTypeFromFileName="application/vnd.ms-powerpoint.addin.macroEnabled.12"
		Case ".ppm"
			getContentTypeFromFileName="image/x-portable-pixmap"
		Case ".pps"
			getContentTypeFromFileName="application/vnd.ms-powerpoint"
		Case ".ppsm"
			getContentTypeFromFileName="application/vnd.ms-powerpoint.slideshow.macroEnabled.12"
		Case ".ppsx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.presentationml.slideshow"
		Case ".ppt"
			getContentTypeFromFileName="application/vnd.ms-powerpoint"
		Case ".pptm"
			getContentTypeFromFileName="application/vnd.ms-powerpoint.presentation.macroEnabled.12"
		Case ".pptx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.presentationml.presentation"
		Case ".prf"
			getContentTypeFromFileName="application/pics-rules"
		Case ".prm"
			getContentTypeFromFileName="application/octet-stream"
		Case ".prx"
			getContentTypeFromFileName="application/octet-stream"
		Case ".ps"
			getContentTypeFromFileName="application/postscript"
		Case ".psc1"
			getContentTypeFromFileName="application/PowerShell"
		Case ".psd"
			getContentTypeFromFileName="application/octet-stream"
		Case ".psess"
			getContentTypeFromFileName="application/xml"
		Case ".psm"
			getContentTypeFromFileName="application/octet-stream"
		Case ".psp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".pub"
			getContentTypeFromFileName="application/x-mspublisher"
		Case ".pwz"
			getContentTypeFromFileName="application/vnd.ms-powerpoint"
		Case ".qht"
			getContentTypeFromFileName="text/x-html-insertion"
		Case ".qhtm"
			getContentTypeFromFileName="text/x-html-insertion"
		Case ".qt"
			getContentTypeFromFileName="video/quicktime"
		Case ".qti"
			getContentTypeFromFileName="image/x-quicktime"
		Case ".qtif"
			getContentTypeFromFileName="image/x-quicktime"
		Case ".qtl"
			getContentTypeFromFileName="application/x-quicktimeplayer"
		Case ".qxd"
			getContentTypeFromFileName="application/octet-stream"
		Case ".ra"
			getContentTypeFromFileName="audio/x-pn-realaudio"
		Case ".ram"
			getContentTypeFromFileName="audio/x-pn-realaudio"
		Case ".rar"
			getContentTypeFromFileName="application/octet-stream"
		Case ".ras"
			getContentTypeFromFileName="image/x-cmu-raster"
		Case ".rat"
			getContentTypeFromFileName="application/rat-file"
		Case ".rc"
			getContentTypeFromFileName="text/plain"
		Case ".rc2"
			getContentTypeFromFileName="text/plain"
		Case ".rct"
			getContentTypeFromFileName="text/plain"
		Case ".rdlc"
			getContentTypeFromFileName="application/xml"
		Case ".resx"
			getContentTypeFromFileName="application/xml"
		Case ".rf"
			getContentTypeFromFileName="image/vnd.rn-realflash"
		Case ".rgb"
			getContentTypeFromFileName="image/x-rgb"
		Case ".rgs"
			getContentTypeFromFileName="text/plain"
		Case ".rm"
			getContentTypeFromFileName="application/vnd.rn-realmedia"
		Case ".rmi"
			getContentTypeFromFileName="audio/mid"
		Case ".rmp"
			getContentTypeFromFileName="application/vnd.rn-rn_music_package"
		Case ".roff"
			getContentTypeFromFileName="application/x-troff"
		Case ".rpm"
			getContentTypeFromFileName="audio/x-pn-realaudio-plugin"
		Case ".rqy"
			getContentTypeFromFileName="text/x-ms-rqy"
		Case ".rtf"
			getContentTypeFromFileName="application/rtf"
		Case ".rtx"
			getContentTypeFromFileName="text/richtext"
		Case ".ruleset"
			getContentTypeFromFileName="application/xml"
		Case ".s"
			getContentTypeFromFileName="text/plain"
		Case ".safariextz"
			getContentTypeFromFileName="application/x-safari-safariextz"
		Case ".scd"
			getContentTypeFromFileName="application/x-msschedule"
		Case ".sct"
			getContentTypeFromFileName="text/scriptlet"
		Case ".sd2"
			getContentTypeFromFileName="audio/x-sd2"
		Case ".sdp"
			getContentTypeFromFileName="application/sdp"
		Case ".sea"
			getContentTypeFromFileName="application/octet-stream"
		Case ".searchConnector-ms"
			getContentTypeFromFileName="application/windows-search-connector+xml"
		Case ".setpay"
			getContentTypeFromFileName="application/set-payment-initiation"
		Case ".setreg"
			getContentTypeFromFileName="application/set-registration-initiation"
		Case ".settings"
			getContentTypeFromFileName="application/xml"
		Case ".sgimb"
			getContentTypeFromFileName="application/x-sgimb"
		Case ".sgml"
			getContentTypeFromFileName="text/sgml"
		Case ".sh"
			getContentTypeFromFileName="application/x-sh"
		Case ".shar"
			getContentTypeFromFileName="application/x-shar"
		Case ".shtml"
			getContentTypeFromFileName="text/html"
		Case ".sit"
			getContentTypeFromFileName="application/x-stuffit"
		Case ".sitemap"
			getContentTypeFromFileName="application/xml"
		Case ".skin"
			getContentTypeFromFileName="application/xml"
		Case ".sldm"
			getContentTypeFromFileName="application/vnd.ms-powerpoint.slide.macroEnabled.12"
		Case ".sldx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.presentationml.slide"
		Case ".slk"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".sln"
			getContentTypeFromFileName="text/plain"
		Case ".slupkg-ms"
			getContentTypeFromFileName="application/x-ms-license"
		Case ".smd"
			getContentTypeFromFileName="audio/x-smd"
		Case ".smi"
			getContentTypeFromFileName="application/octet-stream"
		Case ".smx"
			getContentTypeFromFileName="audio/x-smd"
		Case ".smz"
			getContentTypeFromFileName="audio/x-smd"
		Case ".snd"
			getContentTypeFromFileName="audio/basic"
		Case ".snippet"
			getContentTypeFromFileName="application/xml"
		Case ".snp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".sol"
			getContentTypeFromFileName="text/plain"
		Case ".sor"
			getContentTypeFromFileName="text/plain"
		Case ".spc"
			getContentTypeFromFileName="application/x-pkcs7-certificates"
		Case ".spl"
			getContentTypeFromFileName="application/futuresplash"
		Case ".src"
			getContentTypeFromFileName="application/x-wais-source"
		Case ".srf"
			getContentTypeFromFileName="text/plain"
		Case ".SSISDeploymentManifest"
			getContentTypeFromFileName="text/xml"
		Case ".ssm"
			getContentTypeFromFileName="application/streamingmedia"
		Case ".sst"
			getContentTypeFromFileName="application/vnd.ms-pki.certstore"
		Case ".stl"
			getContentTypeFromFileName="application/vnd.ms-pki.stl"
		Case ".sv4cpio"
			getContentTypeFromFileName="application/x-sv4cpio"
		Case ".sv4crc"
			getContentTypeFromFileName="application/x-sv4crc"
		Case ".svc"
			getContentTypeFromFileName="application/xml"
		Case ".swf"
			getContentTypeFromFileName="application/x-shockwave-flash"
		Case ".t"
			getContentTypeFromFileName="application/x-troff"
		Case ".tar"
			getContentTypeFromFileName="application/x-tar"
		Case ".tcl"
			getContentTypeFromFileName="application/x-tcl"
		Case ".testrunconfig"
			getContentTypeFromFileName="application/xml"
		Case ".testsettings"
			getContentTypeFromFileName="application/xml"
		Case ".tex"
			getContentTypeFromFileName="application/x-tex"
		Case ".texi"
			getContentTypeFromFileName="application/x-texinfo"
		Case ".texinfo"
			getContentTypeFromFileName="application/x-texinfo"
		Case ".tgz"
			getContentTypeFromFileName="application/x-compressed"
		Case ".thmx"
			getContentTypeFromFileName="application/vnd.ms-officetheme"
		Case ".thn"
			getContentTypeFromFileName="application/octet-stream"
		Case ".tif"
			getContentTypeFromFileName="image/tiff"
		Case ".tiff"
			getContentTypeFromFileName="image/tiff"
		Case ".tlh"
			getContentTypeFromFileName="text/plain"
		Case ".tli"
			getContentTypeFromFileName="text/plain"
		Case ".toc"
			getContentTypeFromFileName="application/octet-stream"
		Case ".tr"
			getContentTypeFromFileName="application/x-troff"
		Case ".trm"
			getContentTypeFromFileName="application/x-msterminal"
		Case ".trx"
			getContentTypeFromFileName="application/xml"
		Case ".ts"
			getContentTypeFromFileName="video/vnd.dlna.mpeg-tts"
		Case ".tsv"
			getContentTypeFromFileName="text/tab-separated-values"
		Case ".ttf"
			getContentTypeFromFileName="application/octet-stream"
		Case ".tts"
			getContentTypeFromFileName="video/vnd.dlna.mpeg-tts"
		Case ".txt"
			getContentTypeFromFileName="text/plain"
		Case ".u32"
			getContentTypeFromFileName="application/octet-stream"
		Case ".uls"
			getContentTypeFromFileName="text/iuls"
		Case ".user"
			getContentTypeFromFileName="text/plain"
		Case ".ustar"
			getContentTypeFromFileName="application/x-ustar"
		Case ".vb"
			getContentTypeFromFileName="text/plain"
		Case ".vbdproj"
			getContentTypeFromFileName="text/plain"
		Case ".vbk"
			getContentTypeFromFileName="video/mpeg"
		Case ".vbproj"
			getContentTypeFromFileName="text/plain"
		Case ".vbs"
			getContentTypeFromFileName="text/vbscript"
		Case ".vcf"
			getContentTypeFromFileName="text/x-vcard"
		Case ".vcproj"
			getContentTypeFromFileName="Application/xml"
		Case ".vcs"
			getContentTypeFromFileName="text/plain"
		Case ".vcxproj"
			getContentTypeFromFileName="Application/xml"
		Case ".vddproj"
			getContentTypeFromFileName="text/plain"
		Case ".vdp"
			getContentTypeFromFileName="text/plain"
		Case ".vdproj"
			getContentTypeFromFileName="text/plain"
		Case ".vdx"
			getContentTypeFromFileName="application/vnd.ms-visio.viewer"
		Case ".vml"
			getContentTypeFromFileName="text/xml"
		Case ".vscontent"
			getContentTypeFromFileName="application/xml"
		Case ".vsct"
			getContentTypeFromFileName="text/xml"
		Case ".vsd"
			getContentTypeFromFileName="application/vnd.visio"
		Case ".vsi"
			getContentTypeFromFileName="application/ms-vsi"
		Case ".vsix"
			getContentTypeFromFileName="application/vsix"
		Case ".vsixlangpack"
			getContentTypeFromFileName="text/xml"
		Case ".vsixmanifest"
			getContentTypeFromFileName="text/xml"
		Case ".vsmdi"
			getContentTypeFromFileName="application/xml"
		Case ".vspscc"
			getContentTypeFromFileName="text/plain"
		Case ".vss"
			getContentTypeFromFileName="application/vnd.visio"
		Case ".vsscc"
			getContentTypeFromFileName="text/plain"
		Case ".vssettings"
			getContentTypeFromFileName="text/xml"
		Case ".vssscc"
			getContentTypeFromFileName="text/plain"
		Case ".vst"
			getContentTypeFromFileName="application/vnd.visio"
		Case ".vstemplate"
			getContentTypeFromFileName="text/xml"
		Case ".vsto"
			getContentTypeFromFileName="application/x-ms-vsto"
		Case ".vsw"
			getContentTypeFromFileName="application/vnd.visio"
		Case ".vsx"
			getContentTypeFromFileName="application/vnd.visio"
		Case ".vtx"
			getContentTypeFromFileName="application/vnd.visio"
		Case ".wav"
			getContentTypeFromFileName="audio/wav"
		Case ".wave"
			getContentTypeFromFileName="audio/wav"
		Case ".wax"
			getContentTypeFromFileName="audio/x-ms-wax"
		Case ".wbk"
			getContentTypeFromFileName="application/msword"
		Case ".wbmp"
			getContentTypeFromFileName="image/vnd.wap.wbmp"
		Case ".wcm"
			getContentTypeFromFileName="application/vnd.ms-works"
		Case ".wdb"
			getContentTypeFromFileName="application/vnd.ms-works"
		Case ".wdp"
			getContentTypeFromFileName="image/vnd.ms-photo"
		Case ".webarchive"
			getContentTypeFromFileName="application/x-safari-webarchive"
		Case ".webtest"
			getContentTypeFromFileName="application/xml"
		Case ".wiq"
			getContentTypeFromFileName="application/xml"
		Case ".wiz"
			getContentTypeFromFileName="application/msword"
		Case ".wks"
			getContentTypeFromFileName="application/vnd.ms-works"
		Case ".WLMP"
			getContentTypeFromFileName="application/wlmoviemaker"
		Case ".wlpginstall"
			getContentTypeFromFileName="application/x-wlpg-detect"
		Case ".wlpginstall3"
			getContentTypeFromFileName="application/x-wlpg3-detect"
		Case ".wm"
			getContentTypeFromFileName="video/x-ms-wm"
		Case ".wma"
			getContentTypeFromFileName="audio/x-ms-wma"
		Case ".wmd"
			getContentTypeFromFileName="application/x-ms-wmd"
		Case ".wmf"
			getContentTypeFromFileName="application/x-msmetafile"
		Case ".wml"
			getContentTypeFromFileName="text/vnd.wap.wml"
		Case ".wmlc"
			getContentTypeFromFileName="application/vnd.wap.wmlc"
		Case ".wmls"
			getContentTypeFromFileName="text/vnd.wap.wmlscript"
		Case ".wmlsc"
			getContentTypeFromFileName="application/vnd.wap.wmlscriptc"
		Case ".wmp"
			getContentTypeFromFileName="video/x-ms-wmp"
		Case ".wmv"
			getContentTypeFromFileName="video/x-ms-wmv"
		Case ".wmx"
			getContentTypeFromFileName="video/x-ms-wmx"
		Case ".wmz"
			getContentTypeFromFileName="application/x-ms-wmz"
		Case ".wpl"
			getContentTypeFromFileName="application/vnd.ms-wpl"
		Case ".wps"
			getContentTypeFromFileName="application/vnd.ms-works"
		Case ".wri"
			getContentTypeFromFileName="application/x-mswrite"
		Case ".wrl"
			getContentTypeFromFileName="x-world/x-vrml"
		Case ".wrz"
			getContentTypeFromFileName="x-world/x-vrml"
		Case ".wsc"
			getContentTypeFromFileName="text/scriptlet"
		Case ".wsdl"
			getContentTypeFromFileName="text/xml"
		Case ".wvx"
			getContentTypeFromFileName="video/x-ms-wvx"
		Case ".x"
			getContentTypeFromFileName="application/directx"
		Case ".xaf"
			getContentTypeFromFileName="x-world/x-vrml"
		Case ".xaml"
			getContentTypeFromFileName="application/xaml+xml"
		Case ".xap"
			getContentTypeFromFileName="application/x-silverlight-app"
		Case ".xbap"
			getContentTypeFromFileName="application/x-ms-xbap"
		Case ".xbm"
			getContentTypeFromFileName="image/x-xbitmap"
		Case ".xdr"
			getContentTypeFromFileName="text/plain"
		Case ".xht"
			getContentTypeFromFileName="application/xhtml+xml"
		Case ".xhtml"
			getContentTypeFromFileName="application/xhtml+xml"
		Case ".xla"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xlam"
			getContentTypeFromFileName="application/vnd.ms-excel.addin.macroEnabled.12"
		Case ".xlc"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xld"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xlk"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xll"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xlm"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xls"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xlsb"
			getContentTypeFromFileName="application/vnd.ms-excel.sheet.binary.macroEnabled.12"
		Case ".xlsm"
			getContentTypeFromFileName="application/vnd.ms-excel.sheet.macroEnabled.12"
		Case ".xlsx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
		Case ".xlt"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xltm"
			getContentTypeFromFileName="application/vnd.ms-excel.template.macroEnabled.12"
		Case ".xltx"
			getContentTypeFromFileName="application/vnd.openxmlformats-officedocument.spreadsheetml.template"
		Case ".xlw"
			getContentTypeFromFileName="application/vnd.ms-excel"
		Case ".xml"
			getContentTypeFromFileName="text/xml"
		Case ".xmta"
			getContentTypeFromFileName="application/xml"
		Case ".xof"
			getContentTypeFromFileName="x-world/x-vrml"
		Case ".XOML"
			getContentTypeFromFileName="text/plain"
		Case ".xpm"
			getContentTypeFromFileName="image/x-xpixmap"
		Case ".xps"
			getContentTypeFromFileName="application/vnd.ms-xpsdocument"
		Case ".xrm-ms"
			getContentTypeFromFileName="text/xml"
		Case ".xsc"
			getContentTypeFromFileName="application/xml"
		Case ".xsd"
			getContentTypeFromFileName="text/xml"
		Case ".xsf"
			getContentTypeFromFileName="text/xml"
		Case ".xsl"
			getContentTypeFromFileName="text/xml"
		Case ".xslt"
			getContentTypeFromFileName="text/xml"
		Case ".xsn"
			getContentTypeFromFileName="application/octet-stream"
		Case ".xss"
			getContentTypeFromFileName="application/xml"
		Case ".xtp"
			getContentTypeFromFileName="application/octet-stream"
		Case ".xwd"
			getContentTypeFromFileName="image/x-xwindowdump"
		Case ".z"
			getContentTypeFromFileName="application/x-compress"
		Case ".zip"
			getContentTypeFromFileName="application/x-zip-compressed"
		Case Else
			getContentTypeFromFileName=""
	End Select
End Function
%>